---
apiVersion: spv.no/v1
kind: AzureKeyVaultSecret
metadata:
  name: minio-azure-storage-secret
  namespace: minio
spec:
  vault:
    name: kv-azusw2-trf-dv-01 # name of key vault
    object:
      # multi-value serect can not create from portal.
      # az keyvault secret set --vault-name kv-XXXXXXX --name MINIO-STORAGE-CRED \
      #   --value '{"accesskey": "XXXXXX", "secretkey": "XXXXXX"}'
      contentType: application/x-json # 'application/x-json' or 'application/x-yaml'
      name: MINIO-STORAGE-CRED # name of the akv object
      type: multi-key-value-secret # akv object type
  output:
    secret:
      name: minio-azure-storage-secret # kubernetes secret name