apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ingress
  labels:
    app: minio
    component: storage
    release: minio
  annotations:
    kubernetes.io/ingress.class: nginx
    # cert-manager.io/cluster-issuer: letsencrypt-staging
    # required to enable large object upload
    # see solution: https://github.com/rancher/rancher/issues/14323#issuecomment-402031802
    # and MinIO issue: https://github.com/minio/minio/issues/7893
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  rules:
  - host: {{ .Values.hosts }}
    http:
      paths:
        - backend:
            service:
              name: minio
              port:
                number: 9000
          path: /(.*)
          pathType: Prefix
  # tls:
  # - hosts:
  #   - {{ .Values.hosts }}
  #   secretName: minio-tls