apiVersion: v2
name: minio-app
description: install and configure minio
type: application
version: 0.1.0
appVersion: 1.0
dependencies:
- name: minio
  version: 8.0.9
  repository: https://helm.min.io/
  condition: minio.enabled